apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rnacos-appset
  namespace: argocd-test
  labels:
    app-group: infrastructure
    managed-by: infra-apps
spec:
  generators:
    - merge:
        mergeKeys:
          - path
        generators:
          - clusters:
              selector:
                matchLabels:
                  region: pvg1
                  stack: s1
              values:
                autoSync: "true"
                syncWave: "10"
                path: clusters/{{name}}/infra/rnacos/
          - git:
              repoURL: git@github.com:zhimanai/gitops-deploy-test.git
              revision: HEAD
              directories:
                - path: clusters/*/infra/rnacos/
  template:
    metadata:
      name: infra-rnacos-{{name}}
      labels:
        cluster: "{{name}}"
        region: "{{metadata.labels.region}}"
        stack: "{{metadata.labels.stack}}"
        app-group: infrastructure
        managed-by: infra-apps
      annotations:
        argocd.argoproj.io/sync-wave: "{{values.syncWave}}"
    spec:
      project: infra-project
      sources:
        - repoURL: git@github.com:zhimanai/gitops-deploy-test.git
          targetRevision: HEAD
          path: clusters/{{name}}/infra/rnacos/
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd-test
      syncPolicy:
        syncOptions:
          - Prune=false
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
